Handle Xcode versioning on an unsupported macOS version
Downloading Xcode 8.3 on macOS 10.11, which is unsupported.
I was crashing in `fetch_version` because I couldn't successfully
run Xcode. The command ran, Ruby saw a 0 exit status, but the
output was empty so I ran into:
  undefined method `split' for nil:NilClass (NoMethodError)

The output isn't pretty because of the tool but it doesn't crash:
  Executable requires at least macOS 10.12, but is being run on macOS 10.11.6, and so is exiting.0.0      (/Applications/Xcode-8.3.app)